version: "2.32.4"

services:
  job-search-app-dev:
    build:
      context: .
      target: dev
    container_name: "job-search-app-dev-cont"
    ports:
      - "4000:8000"
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules inside the container
    env_file:
      - ./.env
